#!/bin/bash

LAB=lab7

(make clean; make)

total=0
totalmax=0

rm -f total.txt *out total.txt

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  totalmax=`expr $totalmax + $grade`;

  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"
  
  echo "======= $descr ==========="
  ./$prog $args < $testinput > $prog.out
  ./$prog.org $args< $testinput > $prog.org.out
  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      cat $prog.out
      echo Test passed...;
      printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo ------ Your Output ----------
      cat $prog.out
      echo ------ Expected Output ------
      cat $prog.org.out
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  fi
  echo
}

# List of tests running
runtest TreeDictionaryTest "test1" none 6
runtest TreeDictionaryTest "test2" none 6
runtest TreeDictionaryTest "test3" none 6
runtest TreeDictionaryTest "test4" none 6
runtest TreeDictionaryTest "test5" none 6
runtest TreeDictionaryTest "test6" none 6
runtest TreeDictionaryTest "test7" none 6
runtest TreeDictionaryTest "test8" none 6
runtest TreeDictionaryTest "test9" none 6
runtest WordIteratorTest "test1" none 8
runtest WordIteratorTest "test2" none 6 
runtest WordIteratorTest "test3" none 8
runtest WordCounter "hamlet-short.txt" none 8
runtest WordCounter "hamlet-long.txt" none 8
runtest WordCounter "cosmos.txt" none 8

echo > total.out
echo >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: $LAB. $USER   " >> total.out
date >> total.out
echo   "-------------------------------------------------" >> total.out
cat total.txt >> total.out >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: $LAB. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
cat total.out >> .local.total.out

#Do not remove or comment these lines. They are used for monitoring progress.
labout=/homes/cs240/LABOUT/$LAB/$USER/total.txt
cat total.out >> $labout
git add -A  >> .local.git.out
git commit -a -m "$total of $totalmax" >> .local.git.out


